---
all:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    # ansible_python_interpreter: "/usr/bin/env python"
    config_path: "{{ playbook_dir }}/values.yaml"

    # Deploy into Openshift
    # ==================
    # Note: openshift_host can use the format https://URL:PORT
    # Note: openshift_token can be used for token authentication
    # ==================
    # openshift_host: ''
    # openshift_skip_tls_verify: true
    # openshift_user: ''
    # openshift_password: ''
    # openshift_token: ''