---
- name: Deploy SSO with a database
  hosts: all
  gather_facts: true
  vars_files:
    - ./values.yaml
  tasks:
    - import_role:
        name: openshift-prepare
      tags: always
    - import_role:
        name: crunchydata-postgres-operator
      tags: crunchydata
    - import_role:
        name: sso
      tags: always