kind: Service
apiVersion: v1
metadata:
  name: postgres-operator
spec:
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    name: postgres-operator
    vendor: crunchydata
  type: ClusterIP
  sessionAffinity: None